name: yuki-no

on:
  # Schedule the interval of the checks.
  schedule:
    - cron: '0 * * * *' # Every hour
  # Allow manual trigger (Optional)
  workflow_dispatch:

jobs:
  yuki-no:
    name: Yuki-no
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          # GitHub access token. Required.
          access-token: ${{ secrets.GITHUB_TOKEN }}

          # The head repo to track. This is the repository you want to
          # take a diff. Required.
          head-repo: https://github.com/vitejs/vite.git

          # The branch for the head repo. Optional.
          # Defaults to 'main'.
          head-repo-branch: main

          # The git commit sha of head repo to start tracking. Yuki-no will
          # only track commit from this hash. Required.
          track-from: f19ffbcf3111df45206e95909592b2b75ec76e10

          path-starts-with: docs/

          # Labels to add to the issues. You can specify multiple labels.
          # Each label must be separated by a newline. Optional.
          # If empty string('') is provided, no labels will be added.
          # Defaults to 'sync'.
          labels: |
            sync

          # Whether to enable release tracking.
          # When enabled, Yuki-no will track releases for each issue
          # and add comments about release status. Optional.
          # Defaults to 'false'
          release-tracking: true

          # Whether to enable verbose logging.
          # When enabled, Yuki-no will show all log messages including info and success messages.
          # This is useful for debugging.
          # Defaults to 'false'
          verbose: true
